spring.application.name=optiway

<<<<<<< HEAD
# Conexión a la base de datos PostgreSQL en Supabase
spring.datasource.url=jdbc:postgresql://aws-0-us-west-2.pooler.supabase.com:5432/postgres
spring.datasource.username=postgres.cehzzcvnkiuvkabglrzp
spring.datasource.password=AQUI_TU_CONTRASEÑA_DE_POSTGRESQL
=======
spring.datasource.url=jdbc:postgresql://aws-0-us-west-2.pooler.supabase.com:5432/postgres
spring.datasource.username=postgres.cehzzcvnkiuvkabglrzp
spring.datasource.password=${DB_PASSWORD}
>>>>>>> b7e1487e4220698c3bb4af22a9d72bef148dbc94
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
<<<<<<< HEAD

# Configuración de Auth y API de Supabase
spring.security.oauth2.resourceserver.jwt.issuer-uri=https://cehzzcvnkiuvkabglrzp.supabase.co/auth/v1
supabase.url=https://cehzzcvnkiuvkabglrzp.supabase.co
supabase.service-role-key=sb_publishable_-4TvQX5Ybgs6oX7HawE-LA_Uyk1FzJw
supabase.invite-redirect-url=http://localhost:8080/set-password.html
=======
spring.web.error.include-message=always
spring.web.error.include-binding-errors=always
spring.security.oauth2.resourceserver.jwt.issuer-uri=https://${SUPABASE_PROJECT_REF:cehzzcvnkiuvkabglrzp}.supabase.co/auth/v1
supabase.url=https://${SUPABASE_PROJECT_REF:cehzzcvnkiuvkabglrzp}.supabase.co
supabase.service-role-key=${SUPABASE_SERVICE_ROLE_KEY}
supabase.invite-redirect-url=${SUPABASE_INVITE_REDIRECT_URL:http://localhost:8080/set-password.html}
>>>>>>> b7e1487e4220698c3bb4af22a9d72bef148dbc94
