spring.application.name=optiway

# Conexión a la base de datos PostgreSQL en Supabase
spring.datasource.url=jdbc:postgresql://aws-0-us-west-2.pooler.supabase.com:5432/postgres
spring.datasource.username=postgres.cehzzcvnkiuvkabglrzp
spring.datasource.password=AQUI_TU_CONTRASEÑA_DE_POSTGRESQL
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Configuración de Auth y API de Supabase
spring.security.oauth2.resourceserver.jwt.issuer-uri=https://cehzzcvnkiuvkabglrzp.supabase.co/auth/v1
supabase.url=https://cehzzcvnkiuvkabglrzp.supabase.co
supabase.service-role-key=sb_publishable_-4TvQX5Ybgs6oX7HawE-LA_Uyk1FzJw
supabase.invite-redirect-url=http://localhost:8080/set-password.html